/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIdIndexRouteImport } from './routes/$categoryId/index'
import { Route as CategoryIdToolIdRouteImport } from './routes/$categoryId/$toolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdIndexRoute = CategoryIdIndexRouteImport.update({
  id: '/$categoryId/',
  path: '/$categoryId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdToolIdRoute = CategoryIdToolIdRouteImport.update({
  id: '/$categoryId/$toolId',
  path: '/$categoryId/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$categoryId/$toolId': typeof CategoryIdToolIdRoute
  '/$categoryId/': typeof CategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$categoryId/$toolId': typeof CategoryIdToolIdRoute
  '/$categoryId': typeof CategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$categoryId/$toolId': typeof CategoryIdToolIdRoute
  '/$categoryId/': typeof CategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$categoryId/$toolId' | '/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$categoryId/$toolId' | '/$categoryId'
  id: '__root__' | '/' | '/$categoryId/$toolId' | '/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryIdToolIdRoute: typeof CategoryIdToolIdRoute
  CategoryIdIndexRoute: typeof CategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categoryId/': {
      id: '/$categoryId/'
      path: '/$categoryId'
      fullPath: '/$categoryId/'
      preLoaderRoute: typeof CategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categoryId/$toolId': {
      id: '/$categoryId/$toolId'
      path: '/$categoryId/$toolId'
      fullPath: '/$categoryId/$toolId'
      preLoaderRoute: typeof CategoryIdToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryIdToolIdRoute: CategoryIdToolIdRoute,
  CategoryIdIndexRoute: CategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
